//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuthorizationRole
    {
        public tAuthorizationRole()
        {
            this.tUsers = new HashSet<tUser>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<tUser> tUsers { get; set; }
    }
}
