//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComment
    {
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Text { get; set; }
        public int DocumentVersionId { get; set; }
        public int UserId { get; set; }
    
        public virtual tDocumentVersion tDocumentVersion { get; set; }
        public virtual tUser tUser { get; set; }
    }
}
