//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDocument
    {
        public tDocument()
        {
            this.tUserDocuments = new HashSet<tUserDocument>();
            this.tDocumentVersions = new HashSet<tDocumentVersion>();
            this.tKeywords = new HashSet<tKeyword>();
        }
    
        public int Id { get; set; }
        public int Version { get; set; }
        public System.Guid Guid { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public bool IsValid { get; set; }
        public bool IsArchived { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual ICollection<tUserDocument> tUserDocuments { get; set; }
        public virtual ICollection<tDocumentVersion> tDocumentVersions { get; set; }
        public virtual ICollection<tKeyword> tKeywords { get; set; }
    }
}
