//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tKeyword
    {
        public tKeyword()
        {
            this.tDocuments = new HashSet<tDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tDocument> tDocuments { get; set; }
    }
}
