//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public tUser()
        {
            this.tComments = new HashSet<tComment>();
            this.tUserDocuments = new HashSet<tUserDocument>();
        }
    
        public int Id { get; set; }
        public int Version { get; set; }
        public System.Guid Guid { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public bool HasEmptyPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string ContactPhone { get; set; }
        public string OfficeNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsValid { get; set; }
        public int AuthorizationRoleId { get; set; }
    
        public virtual tAuthorizationRole tAuthorizationRole { get; set; }
        public virtual ICollection<tComment> tComments { get; set; }
        public virtual ICollection<tUserDocument> tUserDocuments { get; set; }
    }
}
