//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserDocument
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DocumentId { get; set; }
        public bool IsReading { get; set; }
        public bool IsWriting { get; set; }
        public int DocumentAccessRightId { get; set; }
    
        public virtual tDocument tDocument { get; set; }
        public virtual tDocumentAccessRight tDocumentAccessRight { get; set; }
        public virtual tUser tUser { get; set; }
    }
}
